# Pytorch Exercise


1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor "x" from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

In [2]:
# number 1
import numpy as np
import torch
import sys

In [15]:
# number 2
def set_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)

In [16]:
# number 3
set_seed(42)
arr = np.random.randint(0, 5, size=6)   # 6 random integers between 0 and 5
print("NumPy array (arr):\n", arr)

NumPy array (arr):
 [3 4 2 4 4 1]


In [17]:
# number 4
x = torch.from_numpy(arr)
print("\nTensor x:\n", x)


Tensor x:
 tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [18]:
# number 5
x = x.to(torch.int64)
print("\nTensor x (int64):\n", x)


Tensor x (int64):
 tensor([3, 4, 2, 4, 4, 1])


In [24]:
# number 6
x = x.reshape(3, 2)
print("\nTensor x reshaped (3x2):\n", x)


Tensor x reshaped (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [25]:
# number 7
right_col = x[:, 1]
print("\nRight-hand column:\n", right_col)


Right-hand column:
 tensor([4, 4, 1])


In [26]:
# number 8
x_squared = x ** 2   # or torch.square(x)
print("\nSquared values of x:\n", x_squared)


Squared values of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [27]:
# number 9
set_seed(42)
y = torch.randint(0, 5, (2, 3))
print("\nTensor y (2x3):\n", y)


Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])


In [28]:
# number 10
product = torch.matmul(x, y)
print("\nMatrix product (x @ y):\n", product)


Matrix product (x @ y):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
